### ISSUE TITLE
Issue parsing multiple formulas in one line

### ISSUE THREAD

**Issue by tgrosinger** [tgrosinger/md-advanced-tables#12]
For example: `<!-- TBLFM: $5=($4/$2);%.2f::$6=($3/$4);%.2f -->`

**Comment by ccc-dvansevenant** [comment]
Ah, known issue, then. Good stuff. I was beginning to think I was losing my mind when my attempt at this formula failed:

`<!-- TBLFM: @2$4..@>$4=((@+1$5-$5)/60)::@2$4..@>$4=if($4<0, 0, $4);%.2f -->`
