### ISSUE TITLE
Sorting numbers

### ISSUE THREAD

**Issue by Faris999** [tgrosinger/md-advanced-tables#17]
Sorting is done alphabetically. I want to sort the value of the number. I tried formatting the number using leading zeros, but it doesn't work.
![image](https://user-images.githubusercontent.com/28823677/112241078-23d61c80-8c7c-11eb-8124-92cd9a138df5.png)

**Comment by tgrosinger** [comment]
This was fixed in ca8b4798c4559e69888b3d7b626bc307ac02f144
Thank you.
