### ISSUE TITLE
Feature Request: Grid Tables

### ISSUE THREAD

**Issue by carmo-lucas** [tgrosinger/md-advanced-tables#19]
I've been using Advanced tables a lot and I really like it! 
Thanks for providing such a useful tool. 

Latly I've been using Obsidian to edit some more complex files and convernting them do pdf using pandoc which has great support for markdown tables including grid tables.

I wonder if it would be possible to add the following syntax to the table formatter.
(grabbed this example from pandoc's user manual)

This format allows multiline rows and wraps text automatically when converting with pandoc.

```
+---------------+---------------+--------------------+
| Fruit         | Price         | Advantages         |
+===============+===============+====================+
| Bananas       | $1.34         | built-in wrapper   |
|               |               | bright color       |
+---------------+---------------+--------------------+
| Oranges       | $2.10         | - cures scurvy     |
|               |               | - tasty            |
+---------------+---------------+--------------------+
```

**Comment by carmo-lucas** [comment]
I've seen issues #35, #86, #54 (all closed) and the difference is that I'm not interested rendering these tables in Obsidian, just wish there was a way to generate this table structure inside the Obsidian editor.

**Comment by tgrosinger** [comment]
@carmo-lucas, thanks for the suggestion. I do not think I will have time to work on this feature, however I like the idea and would be appreciative if someone wanted to take this project on.

**Comment by tgrosinger** [comment]
@carmo-lucas, this plugin is really focused only on markdown tables right now. Maybe it could get extended in the future, but I don't have plans to do that at this time.

In the mean time, it might be possible that https://github.com/aidenlx/table-extended would add the features that you are looking for? I know it adds support for column spans for example.
