### ISSUE TITLE
Formula format apparently cannot include thousands separator or currency prefix

### ISSUE THREAD

**Issue by khorton** [tgrosinger/md-advanced-tables#21]
It does not appear possible to define a format for a formula output that includes thousands separator or currency prefix.  I would hope to have output formatted like "$75,000".

**Comment by luckman212** [comment]
Dupe of #20 ?

**Comment by khorton** [comment]
> Dupe of #20 ?

Yes, a dupe. I'm not sure how I managed to enter this twice.  I'll close this one.
