### ISSUE TITLE
Support dates and times in formulas

### ISSUE THREAD

**Issue by graysonarts** [tgrosinger/md-advanced-tables#31]
I'd love to be able to calculate "Days since" for a column where I'm using it to track chores that need to be done around the house. I'd love to be able to do something like:

| thing | date | days since |
|------|------|------------|
| Thing 1 | 2021-08-29 | `$-1 - today()` |

And have it render as:

| thing | date | days since |
|------|------|------------|
| Thing 1 | 2021-08-29 | 1 day |

**Comment by mayukhc** [comment]
+1 for this request. It would be great to be able to time diff like

| START  | END   | DURATION  |
| ----- | ----- | ----- |
| 09:45 | 10:30 | 45 |

**Comment by tgrosinger** [comment]
Be sure to check out the comments in #45 when implementing this.
Consider the difference between times and durations.
