### ISSUE TITLE
I cant get the formula to work

### ISSUE THREAD

**Issue by sebfischer83** [tgrosinger/md-advanced-tables#32]
Hi,

I had this table
 | Xiaomi                   | 260     | 600  | 15   | M        |           |          |
And I want to subtract the 260 from the 600 and this for every row in the table... I try but I cant figure out how, and no example seems to fit

**Comment by khorton** [comment]
This works for me:

| Item   | Col 2 | Col 3 | Col 4 | Col 5 |     |     |
|:------ | -----:| -----:| -----:| ----- | ---:| --- |
| Xiaomi |   260 |   600 |    15 | M     |     |     |
| Row 2  |   360 |   600 |    15 | M     |     |     |

**Comment by sebfischer83** [comment]
Sorry cant see the forumla :)

**Comment by khorton** [comment]
Hmm.  I didn't realize Github would display the formatted version.  

`| Item   | Col 2 | Col 3 | Col 4 | Col 5 | Result |     |
|:------ | -----:| -----:| -----:| ----- | ------:| --- |
| Xiaomi |   260 |   600 |    15 | M     |        |     |
| Row 2  |   360 |   600 |    15 | M     |        |     |
`

**Comment by sebfischer83** [comment]
Thanks, I hoped there was something like do this for every row
