### ISSUE TITLE
Is an Index column possible?

### ISSUE THREAD

**Issue by PipeItToDevNull** [tgrosinger/md-advanced-tables#33]
This is an "org mode" [source](https://stackoverflow.com/questions/9267050/how-to-achieve-a-row-index-column-in-emacs-org-mode-using-a-calc-column-rule) I believe it relies on `@#` which I do not see in the docs. I assume, with the current implementation this is not possible?

```
| row | data |
|-----+------|
| 2   | 0303 |
| 3   | 5123 |
| 4   | 41   |
| 5   | 4234 |
#+TBLFM: $1=@#
```

**Comment by tgrosinger** [comment]
Duplicate of #13
