### ISSUE TITLE
Advanced calculations not working

### ISSUE THREAD

**Issue by itpropro** [tgrosinger/md-advanced-tables#34]
I just tried to migrate some simple org-mode formulas to markdown and it seems like some operators are not getting parsed. I just tried a few, but mainly these two stopping me from using my formulas:
- ^ (to the power of) 
- % (modulus)

Is this known behavior or is there something broken?

Edit: Here is an example: `<!-- TBLFM: @2$4..@>=($-1*(0.53^$<));%.2f -->`

**Comment by tgrosinger** [comment]
This plugin definitely does not have a complete implementation of Org mode formulas. Currently the only operators supported are `+_*/`. I'll move this issue into the other Github repo where these operators can be added though.

**Comment by gernotstarke** [comment]
even simple additions in one column don't work for me (the example from the docs...):

| Item              | Grams |
| ----------------- | ----- |
| Whole Wheat Flour | 110   |
| Bread Flour       | 748   |
| Warm Water        | 691   |
| Salt              | 18    |
| Starter           | 40    |
| **Total Grams**   |       |


does NOT work :-(

**Comment by ccc-dvansevenant** [comment]
> even simple additions in one column don't work for me (the example from the docs...):
> 
> Item	Grams
> Whole Wheat Flour	110
> Bread Flour	748
> Warm Water	691
> Salt	18
> Starter	40
> **Total Grams**	
> does NOT work :-(

What does your formula for this look like?

**Comment by itpropro** [comment]
@tgrosinger we can close this issue as long as you don't want to track the status of additional calculation here (like ^ and
%).

**Comment by BenjaminBlankertz** [comment]
> consider it resolved, I did not know that I have to press the evaluate button in Obsidian...
> sorry

I had the same problem. Thanks for the hint. It seems that it is not prominently mentioned - may be add it to the "Formulas in Markdown Tables" page.

**Comment by geek-merlin** [comment]
I bumped into this too. Posterity may benefit from documenting this prominently.
