### ISSUE TITLE
Readability Fix

### ISSUE THREAD

**Issue by InoueTomoe** [tgrosinger/md-advanced-tables#41]
Hi, 
just discovered your obsidian plugin (Advanced Tables) and I really like it so far!

I do have a slight problem though, because I use it for words and infos so sometimes the tables can get really long horizontally, and half the time the page has trouble sliding entirely to the right, so when I reach the edge I sometimes have to write without being able to see what I'm writing and going back to correct things is also difficult.
![Screenshot 2022-01-13 233104](https://user-images.githubusercontent.com/53232787/149419845-50cc0808-c2ca-48ae-8888-efbb2b7a9549.jpg)
![Screenshot 2022-01-13 233317](https://user-images.githubusercontent.com/53232787/149419860-c3aa4ab6-9282-4769-b997-c75a1485a86b.jpg)

Would it be possible to add one of those sliding things one can move with a mouse?
![Screenshot 2022-01-13 235709](https://user-images.githubusercontent.com/53232787/149422003-8bb606a5-4025-41a2-9cb3-328d2e8bbde0.jpg)

And would it be possible to make the syntax understand that we may need a row to have a bigger height, for example by adding a new type of "enter" key (ae: shift-enter) that would not go to the next row but just make the row we're in bigger? This way we can have 2, 3, 4 lines of text in each cell of said row directly in the editing mode of the page, instead of having an infinity of <-br-> in a straight line, thus the tables might be a tiny bit smaller horizontally as well.

Also whenever the table creates bigger cells on its own, the lines of the table don't render properly anymore : 
![Screenshot 2022-01-13 233951](https://user-images.githubusercontent.com/53232787/149420248-c42810d2-a4e6-4d4a-bc0c-f5648e48e4ed.jpg)

In any case thank you for your awesome work!

**Comment by tgrosinger** [comment]
Hello,
Thank you for the suggestions. This plugin really only handles how the data in the table are formatted, now how they are rendered. It doesn't add any new table syntax to support multiple lines in tables.
