### ISSUE TITLE
How to disable automatic header/title row?

### ISSUE THREAD

**Issue by k8seren** [tgrosinger/md-advanced-tables#48]
Hi! Not sure how to describe this, so I will do my best. 

I like to format my daily events as a table on my daily note. However, it seems to always create this blank/dashed row, so my first even is "dimmed" and I can't seem to remove it or disable this setting. 

```
| 9:00 AM  | 11:00 AM | event          |
| -------- | -------- | ------------------------------ |
| 11:00 AM | 12:00 PM | event 2                  |
| 12:00 PM | 12:30 PM | Lunch                          |
| 12:45 PM | 2:15 PM  | event 3 |
| 2:30 PM  | 3:30 PM  | event 4 |
```

^ See the ---- filled 2nd row

The live display looks like this: 
<img width="649" alt="image" src="https://user-images.githubusercontent.com/8378030/187945303-c5496e44-ee87-4501-b9f6-7173a4087a56.png">

sorry if this is a dumb question or something easily disabled. If that is the case, can someone kindly point me to the setting? 
If this isn't a setting, can you please add it? 

Thanks for your help.

**Comment by HyperEpsilon** [comment]
The dashed lines are how markdown syntax represents a table, and the row above is the title row.

What I tend to do is to just leave the header row blank, which leaves a slight double row at the top, but I don't mind that.

**Comment by tgrosinger** [comment]
Unfortunately this is a limitation of Obsidian or Markdown itself. They seem to require a header row in order to consider it a table.

Leaving the heading empty is what I do as well :)
