### ISSUE TITLE
Can't use previous row `@-1` in formula body

### ISSUE THREAD

**Issue by joelmeyerhamme** [tgrosinger/md-advanced-tables#54]
Attempting to calculate the running sum of a list of transactions requires a reference to the sum in the previous row. Apparently, any of `@-1` the formula body leads to a syntax error, both formulas in the examble fail, but various combinations without `@-1` do not.

```md
|    In |  Out | Saldo |
| -----:| ----:| -----:|
|  0.00 | 0.00 |       |
| 30.00 |      |       |
|  4.00 |      |       |
|       | 0.50 |       |
<!-- TBLFM: $>=(@-1) -->
<!-- TBLFM: $>=(@-1 + $-2 - $-1);%.2f -->
```

**Comment by khorton** [comment]
There is one requirement that I don't think is described in the docs: when doing a calculation with multiple operators, each sub calculation must be enclosed in parentheses.

Does this do what you want:

`
|    In |  Out | Saldo |
| -----:| ----:| -----:|
|  0.00 | 0.00 |  0.00 |
| 30.00 |      | 30.00 |
|  4.00 |      | 34.00 |
|       | 0.50 | 33.50 |
`

**Comment by tgrosinger** [comment]
That definitely could be more clear in the documentation, and you are exactly right. All arithmetic operations must be in parenthesis. See the examples [in the docs|https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md#algebraic-operations]

Thanks for answering this @khorton.

**Comment by joelmeyerhamme** [comment]
Interesting point, but as described in the original question, any formula including the `@-1` (previous row) reference fails.
