### ISSUE TITLE
I can't make any of your examples work.

### ISSUE THREAD

**Issue by claylj** [tgrosinger/md-advanced-tables#58]
| Item                         | Grams |
| ----------------------| ------  |
| Whole Wheat Flour | 110     |
| Bread Flour              | 748     |
| Warm Water            | 691     |
| Salt                          | 18       |
| Starter                     | 40       |
| **Total Grams**      |            |

I pasted this example from the help file into a Obsidian Note, and it doesn't do anything. I've tried the other examples as well with no luck. It doesn't seem to work here ether.
I have the Advance Tables Plugin installed and enabled.
Any help would appreciated.

**Comment by khorton** [comment]
Are you opening the Advanced Tables pane and clicking the "fx' icon?  The formulae are not evaluated until you click that icon.

**Comment by claylj** [comment]
Yep, that was the problem. I read everything I could find on formulas but never saw that.

Thanks!
