### ISSUE TITLE
After updating the plugin none of my tables formulas are working!

### ISSUE THREAD

**Issue by BobWs** [tgrosinger/md-advanced-tables#67]
Hi,
After updating the plugin none of my tables formulas are working anymore! 
I have several tables with a calculation formula and none of them work after the plugin update.
Any idea what is going on and how I can fix this?

```
## e.g.
| product | amount | price | total |
| ------- | ------:| -----:| ------:|
| banana  |      1 |     2 |      3 |
| apple   |      3|     3 |      5 |
|         |        |       |      8 |
<!-- TBLFM: @2$4=sum(@2$2..@2$3) -->
<!-- TBLFM: @3$4=sum(@3$2..@3$3) -->
<!-- TBLFM: @>$4=sum(@1..@3) -->
```

**Comment by khorton** [comment]
This works:

```
| product | amount | price | total |
| ------- | ------:| -----:| -----:|
| banana  |      1 |     2 |     2 |
| apple   |      3 |     3 |     9 |
|         |        |       |    11 |
<!-- TBLFM: $4=($2 * $3) -->
<!-- TBLFM: @>$4=sum(@I..@-1) -->```

**Comment by BobWs** [comment]
> This works:

I don't get it, all my formulas were working before, so it looks like I need to adjust all my tables! I have quite some tables with formulas...not cool!😔😞

**Comment by khorton** [comment]
I don't understand how your previous formulas worked, as the math doesn't match the column headings.  For each of row 2 and three, the original formula had the total as the sum of the amount and the price.   My version says that column four is column 2 * column three.  And the total is the sum of the other values in column 4

Your original version will work if you change the last formula to sum(@2..@3).  @1 is the header row, which has no numbers.

**Comment by tgrosinger** [comment]
Hi @BobWs,

It looks like the only change needed to make your formulas work is to change the last formulas `@1` to `@2`. As was mentioned by @khorton, `@1` refers to the header, not the first row of data.

```
| product | amount | price | total |
| ------- | ------:| -----:| -----:|
| banana  |      1 |     2 |     3 |
| apple   |      3 |     3 |     6 |
|         |        |       |     9 |
<!-- TBLFM: @2$4=sum(@2$2..@2$3) -->
<!-- TBLFM: @3$4=sum(@3$2..@3$3) -->
<!-- TBLFM: @>$4=sum(@2..@3) -->
```

Additionally, you could remove the need to have a forumula for each row of the table by altering it like this (also as suggested by @khorton):

```
| product | amount | price | total |
| ------- | ------:| -----:| -----:|
| banana  |      1 |     2 |     3 |
| apple   |      3 |     3 |     6 |
|         |        |       |     9 |
<!-- TBLFM: $4=($2 + $3) -->
<!-- TBLFM: @>$4=sum(@I..@-1) -->
```

This works because the formulas are evaluated sequentially. So the last formula will overwrite the value in column 4 with the sum for that column.

Let me know if you have any further questions.
