### ISSUE TITLE
Shorthand for offsets from table bottom

### ISSUE THREAD

**Issue by tgrosinger** [tgrosinger/md-advanced-tables#7]
Instead of writing `@>-2`, I could write `@-3`. In words, this means instead of "2 up from the last row" I could write "3rd to last row".

The same behavior should be implemented for columns.

**Comment by tgrosinger** [comment]
Done with the formulas rewrite. Syntax is `@-2` for rows and `$-2` for columns.

**Comment by geek5nan** [comment]
Great job! This plugin is really I want, bug I noticed some issues below.

* Fomula  `<!-- TBLFM: @>$>-1=22 -->` cound not be parsed
* Fomula  `<!-- TBLFM: @>$-1=22 -->` cound not be parsed

I had read the document, seems like `@-2` and `@>-2` is a relative position for **destination** which can not be use before `=`.

In my option, maybe `@>-2` is not should to shorthand to `@-2` for the reason below
* `@-2` means `2 up from the **destination** row`, `@-2` **MUST** occured in rvalue.
* `@>-2` means `2 up from the **last** row`, `@>-2` can occured any value.
