### ISSUE TITLE
Truncate decimal places

### ISSUE THREAD

**Issue by KzBeck** [tgrosinger/md-advanced-tables#74]
I have an average of numbers for exercise. The number is something like this: 1.8553892215568862275. Is there a way to truncate the cell results to 3 or 4 decimal places? For example, 1.855.

**Comment by KzBeck** [comment]
I just found the answer (that I overlooked).

**Comment by sboulema** [comment]
I ran into the same... sometimes reading ALL the documentation is difficult.
To help the next person running into this, read this paragraph: https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md#formatting-options
