### ISSUE TITLE
Adding numbers from 1 cell

### ISSUE THREAD

**Issue by pita500** [tgrosinger/md-advanced-tables#77]
Hi, thank you very much for this plug-in.  I am learning a lot with the formulas but I am stuck.  Is it possible to add several numbers from 1 cell ?

| Epicerie   | Montant |
| ---------- | ------- |
| nourriture | 10+20+30|
| Total         |               |

Please advise

thank you

**Comment by tgrosinger** [comment]
Unfortunately this is not currently possible with this library.

**Comment by pita500** [comment]
Thank you for the prompt reply
