### ISSUE TITLE
Add ability to reference values in other tables

### ISSUE THREAD

**Issue by tgrosinger** [tgrosinger/md-advanced-tables#9]
This would definitely be achievable from other tables within that same file.

For tables in other files, it would require a new interface value on the text editor that would allow this library to pull the other file contents.

**Comment by tgrosinger** [comment]
Not planning on adding this.

**Comment by Teighe** [comment]
@tgrosinger how do you reference a different table in the same .md file? I have multiple tables for different stages of a project. In each table are multiple substages with an hourly estimate on the same row, in the last column. Those numbers total at the bottom.  But I would also like a total of the collected totals of each top level stage estimates, so I know if the whole project is on track.
